import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

import { renderSchemaDocument } from '@piano/score-format'

/**
 * The published JSON Schema is never behind the validator the app runs.
 *
 * The document a model reads and the code that refuses its output come from
 * one zod declaration. That only stays true if something checks: a schema
 * regenerated by hand after the third change is one regenerated after the
 * first two and not the third, and nobody finds out until a model writes a
 * field the document said was fine.
 *
 * It lives here rather than in the package's own tests because the package is
 * deliberately free of node and DOM types -- it runs in main, in the renderer
 * and in the MCP server alike -- and reading a file from disk is exactly the
 * kind of thing it must not learn to do.
 */
const schemaFile = fileURLToPath(
  new URL('../packages/score-format/schema/score.schema.json', import.meta.url),
)

let checkedIn: string
try {
  checkedIn = await readFile(schemaFile, 'utf8')
} catch {
  process.stderr.write('the JSON Schema has never been generated; run `npm run schema`\n')
  process.exit(1)
}

if (checkedIn !== renderSchemaDocument()) {
  process.stderr.write(
    'the checked-in JSON Schema is behind the zod schema it is generated from.\n' +
      'Run `npm run schema` and commit the result: the document a model reads must not\n' +
      'describe a format the validator no longer accepts.\n',
  )
  process.exit(1)
}

process.stdout.write('json schema: the published document matches the validator\n')
